interface TeamMember {
  id: number;
  name: string;
  role: string;
  image: string;
  linkedin?: string;
  github?: string;
}


export const teams: Record<string, TeamMember[]> = {
  'President & Vice President': [
    {
      id: 1,
      name: 'Sufia Sayyed',
      role: 'President',
      image: '/president.jpg',
      linkedin: 'https://www.linkedin.com/in/sufia-sayyed',
      github: 'https://instagram.com/sufii._02',
    },
    {
      id: 2,
      name: 'Swapnil Birajdar',
      role: 'Vice President',
      image: '/Swapnil.jpg',
      linkedin: 'https://www.linkedin.com/in/swapnil-birajdar-9657b1347',
      github: 'https://instagram.com/itswapnil.x',
    },
  ],
  'Technical Team': [
    {
      id: 3,
      name: 'Arham Boonlia',
      role: 'Head',
      image: '/arham_boonlia.png',
      linkedin: 'https://www.linkedin.com/in/arham-boonlia21',
      github: 'https://instagram.com/arrhham.b_21',
    },
    {
      id: 4,
      name: 'Priyal Khunia',
      role: 'Member',
      image: '/priyal_khunia.png',
      linkedin: 'https://www.linkedin.com/in/priyal-khunia-840316378',
      github: 'https://instagram.com/__priyallllll__',
    },
    {
      id: 5,
      name: 'Kriya Khuniya',
      role: 'Member',
      image: '/kriya_khuniya.png',
      linkedin: 'https://www.linkedin.com/in/kriya-khuniya-322815384',
      github: 'https://instagram.com/kriya_khuniya',
    },
    {
      id: 6,
      name: 'Rohit Sharma',
      role: 'Member',
      image: '/rohit_sharma.png',
      linkedin: 'https://www.linkedin.com/in/rohit-sharma-6256a0220',
      github: 'https://instagram.com/rxhit_stll',
    },
    {
      id: 7,
      name: 'Sriyaan Shetty',
      role: 'Member',
      image: '/Sriyaan.jpg',
      linkedin: 'https://www.linkedin.com/in/sheshanthshetty',
      github: 'https://instagram.com/nextgenai_vu',
    },
    {
      id: 8,
      name: 'Tanish Lande',
      role: 'Member',
      image: '/Tanish.jpg',
      linkedin: 'https://www.linkedin.com/in/tanish-lande-903606312',
      github: 'https://instagram.com/nextgenai_vu',
    },
    {
      id: 9,
      name: 'Rayhaan Ahmed',
      role: 'Member',
      image: '/Rayhaan.jpg',
      linkedin: 'https://www.linkedin.com/in/rayhaan-ahmed-25b956380',
      github: 'https://instagram.com/rayhaanfay',
    },
  ],
  'Social Media Team': [
    {
      id: 10,
      name: 'Shubh Mali',
      role: 'Head',
      image: '/shubh_mali.png',
      linkedin: 'https://www.linkedin.com/in/shubh-mali-3a353a334',
      github: 'https://instagram.com/life_of_btech_student',
    },
    {
      id: 11,
      name: 'Aaroh Dharmadhikari',
      role: 'Member',
      image: '/aaroh_dharmadhikari.jpg',
      linkedin: 'https://www.linkedin.com/in/aarohdharmadhikari',
      github: 'https://instagram.com/aaroh._575',
    },
    {
      id: 12,
      name: 'Manali Maniyar',
      role: 'Member',
      image: '/manali_maniyar.jpg',
      linkedin: 'https://www.linkedin.com/in/manali-maniyar-2188462b4',
      github: 'https://instagram.com/manalii_28',
    },
    {
      id: 13,
      name: 'Ayan Kundlik',
      role: 'Member',
      image: '/ayan_kundlik.jpg',
      linkedin: 'https://www.linkedin.com/in/ayan-kundlik',
      github: 'https://instagram.com/ayan.kundlik',
    },
    {
      id: 14,
      name: 'Omkar Katare',
      role: 'Member',
      image: '/Omkar.jpg',
      linkedin: 'https://www.linkedin.com/in/omkar-katare',
      github: 'https://instagram.com/mr_omkar___96',
    },
    {
      id: 15,
      name: 'Roshani Galande',
      role: 'Member',
      image: '/Roshini.jpg',
      linkedin: 'https://www.linkedin.com/in/roshani-galande-6b4716383',
      github: 'https://instagram.com/roshani.s.g',
    },
  ],
  'Event Management Team': [
    {
      id: 16,
      name: 'Aditya Patil',
      role: 'Head',
      image: '/aditya_patil.png',
      linkedin: 'https://www.linkedin.com/in/aditya-patil-698552347/',
      github: 'https://instagram.com/nextgenai_vu',
    },
    {
      id: 17,
      name: 'Saiprasad Patil',
      role: 'Member',
      image: '/saiprasad_patil.png',
      linkedin: 'https://www.linkedin.com/in/saiprasad-patil-5a46a2385',
      github: 'https://instagram.com/saiprasadpatil7900',
    },
    {
      id: 18,
      name: 'Rajeshwari Nagare',
      role: 'Member',
      image: '/rajeshwari_nagare.png',
      linkedin: 'https://www.linkedin.com/in/rajeshwari-nagare-19a285380',
      github: 'https://instagram.com/rajeshwarii_10',
    },
    {
      id: 19,
      name: 'Prarthana Dhage',
      role: 'Member',
      image: '/prarthana_dhage.jpg',
      linkedin: 'https://www.linkedin.com/in/prarthana-dhage',
      github: 'https://instagram.com/prarthana.dhage021',
    },
    {
      id: 20,
      name: 'Shreyansh Pokarna',
      role: 'Member',
      image: '/shreyansh_pokharna.png',
      linkedin: 'https://linkedin.com/in/shreyansh-pokarna',
      github: 'https://instagram.com/nextgenai_vu',
    },
    {
      id: 21,
      name: 'Pranav Sharma',
      role: 'Member',
      image: '/pranav_sharma.jpg',
      linkedin: 'https://www.linkedin.com/in/pranav-sharma-06a152277',
      github: 'https://instagram.com/pranav_sharma200610',
    },
  ],
  'Public Relations (PR) Team': [
    {
      id: 22,
      name: 'Justin Bardeskar',
      role: 'Head',
      image: '/Justin bardeskar.png',
      linkedin: 'https://www.linkedin.com/in/justin-bardeskar-3011462b2',
      github: 'https://www.instagram.com/justin.k30',
    },
    {
      id: 23,
      name: 'Dhavalsinh Mane',
      role: 'Member',
      image: '/Dhaval.jpg',
      linkedin: 'https://www.linkedin.com/in/dhavalsinh-mane-087069289',
      github: 'https://instagram.com/_dhavxlll',
    },
    {
      id: 24,
      name: 'Sarthak Pardeshi',
      role: 'Member',
      image: '/sarthak_pardeshi.png',
      linkedin: 'https://www.linkedin.com/in/sarthak-pardeshi-77a257348',
      github: 'https://www.instagram.com/sarthak.p_7',
    },
  ],
  'Finance Team': [
    {
      id: 25,
      name: 'Ashish Purohit',
      role: 'Head',
      image: '/Ashish Purohit.png',
      linkedin: 'https://www.linkedin.com/in/ashish-purohit123456',
      github: 'https://instagram.com/ashish_purohit_1220',
    },
    {
      id: 26,
      name: 'Abhay Wagh',
      role: 'Member',
      image: '/Abhay Wagh.png',
      linkedin: 'https://www.linkedin.com/in/abhay-wagh-759b9a2b8',
      github: 'https://instagram.com/waghabhay93',
    },
  ],
};